== Web Integration: iFrame

Mittels iFrame steht eine einfache Möglichkeit zur Einbindung von Karten- und Kartenebenen in Webseiten zur Verfügung.

=== Beispiele
Die Karten(-ebenen) werden mit dem `<iframe>` HTML Element ("inline frame") in eine Webseite eingebunden.  

**Orthofoto als Hintergrundkarte und Grundstücke und Fixpunkte als Kartenebene:**

```
<iframe src='https://grundstuecksinformation.ch/embed/embed.html?bgLayer=ch.so.agi.hintergrundkarte_ortho&layers=ch.so.agi.av.grundstuecke,ch.so.agi.av.fixpunkte&layers_opacity=1,1&E=2607457.049140623&N=1228667.6838281231&zoom=14' width='600' height='450' style='border:0px solid white;'></iframe>
```

+++
<iframe src='https://grundstuecksinformation.ch/embed/embed.html?bgLayer=ch.so.agi.hintergrundkarte_ortho&layers=ch.so.agi.av.grundstuecke,ch.so.agi.av.fixpunkte&layers_opacity=1,1&E=2607457.049140623&N=1228667.6838281231&zoom=14' width='600' height='450' style='border:0px solid white;'></iframe>
+++

**Hintergrundkarte schwarz-weiss und verschiedene Kartenebenen inkl. Prüfperimeter für Erdwärmesonden:**

```
<iframe src='https://grundstuecksinformation.ch/embed/embed.html?bgLayer=ch.so.agi.hintergrundkarte_sw&layers=ch.so.afu.erdwaermesonden.abfrageperimeter,ch.so.afu.gewaesserschutz.zonen_areale,ch.so.afu.altlasten.standorte&layers_opacity=0.35,0.5,0.6&E=2607577.014463918&N=1227885.4209060299&zoom=11' width='600' height='450' style='border:0px solid white;'></iframe>
```

+++
<iframe src='https://grundstuecksinformation.ch/embed/embed.html?bgLayer=ch.so.agi.hintergrundkarte_sw&layers=ch.so.afu.erdwaermesonden.abfrageperimeter,ch.so.afu.gewaesserschutz.zonen_areale,ch.so.afu.altlasten.standorte&layers_opacity=0.35,0.5,0.6&E=2607577.014463918&N=1227885.4209060299&zoom=11' width='600' height='450' style='border:0px solid white;'></iframe>
+++

=== Parameter

- `bgLayer`: Wählt die Hintergrundkarte aus. Es stehen die gleichen Hintergrundkarten wie im Web GIS Client zur Verfügung. Die Namen entsprechen den https://geo.so.ch/api/wmts/1.0.0/WMTSCapabilities.xml[WMTS-Layernamen].
- `layers`: Kommaseparierte Liste für die anzuzeigenden Kartenebenen. Die Namen entsprechen den https://geo.so.ch/api/wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0[WMS-Layername]. Der WMS-Layername entspricht dem Identifier wie er auch in der URL des Web GIS Clients für die jeweilige Kartenebene sichtbar ist.
- `layers_opacity`: Kommaseparierte Liste mit der Opazität des jeweiligen Layers von `layers`. Der Wertebereich geht von 0 (komplett durchsichtig resp. unsichtbar) bis 1 (keine Transparenz).
- `E` / `N`: Koordinatewerte des Kartenmittelpunktes.
- `zoom`: Zoomstufe der Karte. Entspricht den Zoomstufen des https://geo.so.ch/api/wmts/1.0.0/WMTSCapabilities.xml[WMTS] 

=== Objektinformation
TODO

